codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: "50...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "**/testutils.go" # ignore code used only for test scaffolding
  - "testutils/*.go" # ignore code used only for test scaffolding

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
